### ISSUE TITLE
uncatchable exception

### ISSUE THREAD

**Issue by obriat** [hoodoo-digital/locust-influxdb-listener#11]
I initiate InfluxDBListener on @events.init.add_listener and sometimes the InfluxDB is not up, so python throw me exceptions even if I try/catch the function call.
I noticed that the call to influxdb_client in /locust_influxdb_listener/__init__.py", line 55 should be catched and return None.
Am I missing something here ?

```
Traceback (most recent call last):
  File "~/.local/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
...
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
...
  File "~/.local/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f56ba8acc88>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
...
  File "~/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.5', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22locustidb%22&db=locustidb (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f56ba8acc88>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/lib/python3.7/site-packages/locust_influxdb_listener/__init__.py", line 55, in __init__
     self.influxdb_client.create_database(influxDbSettings.database)
   File "/home/locust/.local/lib/python3.8/site-packages/influxdb/client.py", line 746, in create_database
```

**Comment by pjcalvo** [comment]
I will take a look.

**Comment by pjcalvo** [comment]
@obriat I just uploaded a fix. switched to .error instead of .exception to hide the extra information. https://pypi.org/project/locust-influxdb-listener/0.0.5/

**Comment by obriat** [comment]
It didn't fix my issue, I'm a python newbie so maybe my approach is not the right one
I want to wait for influxdb to be ready and just log it if it can't be reach but without stopping my locsut test.

```python
@events.init.add_listener
def locust_init(environment, **kwargs):
...
      influxDBSettings = InfluxDBSettings(
            influx_host=influx_host,
            influx_port='8086',
            user='****',
            pwd='****',
            database='locustidb'
        )
       # try 5 times for a total of 55s
        for i in range(5):
            try:
               InfluxDBListener(env=environment, influxDbSettings=influxDBSettings)
            except:
                wait = i * i 
                log("Try " + i + ": Could not connect to influxdb, wait for" + wait + " seconds and try again.")
                time.sleep(wait) 
                continue 
            else:
                log("Influxdb is available")
                break
        else:
            log("Influxdb is not available")

```

**Comment by pjcalvo** [comment]
@obriat The exception is currently handled by the listener.  So you don't have to catch it in your end [here](https://github.com/hoodoo-digital/locust-influxdb-listener/blob/2753a43c4d36bdfe590b3383071bd1811ace26d6/locust_influxdb_listener/__init__.py#L57).

Make you you update to version 0.0.5, which has the fix for the extra log information....

**Comment by obriat** [comment]
You're right, my package wasn't up to date. 
I also see my other mistake, I took the logger.exception for a real exception. 
So do you know how I can determine if InfluxDBListener is connected ? The object doesn't seem to return any data or state, it just logs the error.

**Comment by pjcalvo** [comment]
I will make it so it returns a true in case of success.. @obriat

**Comment by obriat** [comment]
Here a suggestion: #12

**Comment by obriat** [comment]
I think I find the right process by using the `ping` method and catching its exception:
```python
            influxDBSettings = InfluxDBSettings(
                influx_host='influx_host',
                influx_port='8086',
                user='admin',
                pwd='pass',
                database='locustidb'
            )

            for i in range(1, 6):
                try:
                    # start listener with the given configuration
                    influx = InfluxDBListener(env=environment, influxDbSettings=influxDBSettings)
                    influx.influxdb_client.ping()
                except:
                   # InfluxDBListener does not throw exception but  influx.influxdb_client.ping() do.
                    wait = i * i
                    print("Try n°" + str(i) + ": Could not connect to influxdb, wait for " + str(
                        wait) + " seconds and try again.")
                    time.sleep(wait)  # sleep the script for x seconds and....#

                else:
                    print("Influx (version: " + influx.influxdb_client.ping() + ") is available")
                    break  # ...break out of the loop#
            else:
                print("Influx is not available!")
```

**Comment by pjcalvo** [comment]
Perfect.
